# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project: 'Auth.UnitTests\Auth.UnitTests.csproj'
  TargetFramework: 'net5.0'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(project)'
    command: build
    arguments: '--configuration $(BuildConfiguration) --framework=$(TargetFramework)'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      pip install jwcrypto

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)\Auth.UnitTests\bin\$(buildConfiguration)\$(TargetFramework)\gen-jwt\generate-tokens.ps1'
    arguments: '$(System.DefaultWorkingDirectory)\Auth.UnitTests\bin\$(buildConfiguration)\$(TargetFramework)\gen-jwt'

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'

- task: VSTest@2
  inputs:
    testAssemblyVer2: '$(System.DefaultWorkingDirectory)\Auth.UnitTests\bin\$(buildConfiguration)\$(TargetFramework)\Auth.UnitTests.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: true
