---
apiVersion: v1
kind: Pod
metadata:
  name: dbsqlpod
  namespace: concepto
  labels:
    app: concepto
    tier: db
spec:
  containers:
    - name: dbsql-sha256-1
      image: us-west2-docker.pkg.dev/utility-descent-185119/webapp-repo/dbsql@sha256:1819671b5df7838f39bb580edbea6855e5221006d23488edcc13faad9c35a702
---
apiVersion: v1
kind: Service
metadata:
  name: dbsql
  namespace: concepto
spec:
  clusterIP: None
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: concepto
    tier: db
  sessionAffinity: None
  type: ClusterIP