version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
      - dbsql
  dbsql:
    image: ${DOCKER_REGISTRY-}dbsql:dev
