resources:
- repo: self
  fetchDepth: 1
pool:
  vmImage: ubuntu-16.04
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - WebApp
variables:
  TargetFramework: 'net5.0'
  BuildConfiguration: 'Release'
  DockerImageName: 'webapp'
steps:
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    projects: 'WebApp/WebApp.csproj'
    publishWebProjects: false
    command: publish
    arguments: '--configuration $(BuildConfiguration) --framework=$(TargetFramework)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gar-webapp-repo'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: 'WebApp/Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'