resources:
- repo: self
  fetchDepth: 1
pool:
  vmImage: ubuntu-latest
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - DbUsers
variables:
  TargetFramework: 'netstandard2.0'
  BuildConfiguration: 'Release'
  DockerImageName: 'utility-descent-185119/webapp-repo/dbsql'
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'DbUsers.Build/DbUsers.Build.csproj'
    command: build
    arguments: '--configuration $(BuildConfiguration) --framework=$(TargetFramework)'
    modifyOutputPath: false
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gar-webapp-repo'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: '$(Build.SourcesDirectory)/DbUsers/Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      dev
