resources:
- repo: self
  fetchDepth: 1
pool:
  vmImage: ubuntu-latest
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - WebApp
variables:
  TargetFramework: 'net5.0'
  BuildConfiguration: 'Release'
  DockerImageName: 'us-west2-docker.pkg.dev/utility-descent-185119/webapp-repo/webapp'
steps:
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    projects: 'WebApp/WebApp.csproj'
    publishWebProjects: false
    command: publish
    arguments: '--configuration $(BuildConfiguration) --framework=$(TargetFramework)'
    zipAfterPublish: false
    modifyOutputPath: false
- task: Docker@2
  displayName: 'Login to Container Registry'
  inputs:
    command: login
    containerRegistry: 'gar-webapp-repo'
- task: Docker@2
  displayName: 'Build and push image'
  inputs:
    Dockerfile: '$(Build.SourcesDirectory)/WebApp/Dockerfile'
    command: buildAndPush
    repository: '$(DockerImageName)'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      dev
