steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |-
    REPLACE=$(printf '%s\n' "${_DIGEST}" | sed -e 's/[\/&]/\\&/g')
    sed -i "0,/^\([[:space:]]*image: *\).*/s//\1$REPLACE/;" webapp.yaml
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=Deploy/webapp.yaml
  - --location=us-west2
  - --cluster=autopilot-cluster-eshop
substitutions:
  _DIGEST: none # default value