steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch']
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=/workspace/.git/Deploy/webapp.yaml
  - --location=us-west2
  - --cluster=autopilot-cluster-eshop
