steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['Deploy/replace.sh','${_DIGEST}', '${_FILE}']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=${_FILE}
  - --location=us-west2
  - --cluster=autopilot-cluster-eshop
substitutions:
  _DIGEST: none # default value