CREATE TABLE [dbo].[Roles]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] NVARCHAR(50) NOT NULL, 
    [TenantId] NVARCHAR(20) NULL, 
    CONSTRAINT [FK_Roles_Tenant] FOREIGN KEY (TenantId) REFERENCES Tenants(Id)
)
